site_name: RAP Community of Practice
# site_url: https://example.com
repo_url: https://github.com/dfe-analytical-services/dfe-stats-production-guidance/
repo_name: DfE Statistics Production Guidance
edit_uri: edit/main/docs/
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
  - search
  - mkdocs-jupyter:
      include_source: True
      theme: dark
nav:
  - Home: README.md
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: indigo
  font:
    text: Arial
  logo: images/DfE-logo-landscape.png
  favicon: images/dfefavicon.png
  features:
    - search.share
    - content.code.annotate
    - content.tabs.link
  icon:
    admonition:
      <type>: material/alert
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.tasklist:
      # clickable_checkbox: true
      custom_checkbox: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dfe-analytical-services/dfe-stats-production-guidance/
      name: DfE Analytical Services
  generator: false
copyright: Copyright &copy; 2023 Crown Copyright (DfE Analytical Services)
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
